name: myapp
type: Microsoft.App/containerApps
location: westeurope
properties:
  configuration:
    ingress:
      external: true
      targetPort: 8080
  template:
    containers:
      - name: myapp
        image: atrium5365/myapp:v1
        env:
          - name: CLOUD_PROVIDER
            value: azure
        resources:
          cpu: 0.25
          memory: 0.5Gi